name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Create release zip
        run: |
          mkdir -p vertical-scroll-gallery
          cp -R build vertical-scroll-gallery/
          cp -R *.php vertical-scroll-gallery/
          cp -R readme.txt vertical-scroll-gallery/
          zip -r vertical-scroll-gallery.zip vertical-scroll-gallery

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: vertical-scroll-gallery.zip
          tag_name: ${{ github.run_number }}
          release_name: "Release ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
